### PR TITLE
Save and reselect recently refreshed plugin

### LINKED ISSUE #2: Interaction Improvement
This is a very useful plugin.  However, as I am developing my own plugin I am finding it necessary to have to reload my plugin frequently.  It would be nice if the plugin refresher would continue to stay on last plugin selected. Not too painful, but it would be useful I think especially in the case I described.

### PR DESCRIPTION
**Pull request by Xrayez**
Closes #2.

This allows developers to stay on the recently reloaded plugin during and between editor sessions by making use of plugin custom configuration file which is saved at project settings directory.

Also updated project settings to match with Godot 3.1-stable.
Also works with Godot 3.2-dev.

Disabled non-existing plugin which was used for testing apparently.

### CODE REVIEW

**Comment by willnationsdev** [comment]
Wow, these look like great changes, thanks! I'm curious whether storing the data in EditorSettings is better/worse than ProjectSettings since, after all, plugins themselves (including the plugin refresher) are installed per-project, so 1) the refresher's settings might continue to exist even if the user deletes the only project using that data (clutter) and 2) the recently used plugin will have the same value between projects. Not only does that mean that modifying data in project could affect the editor in a different project, but it also could even end up as invalid data since 2 different projects might not have the same plugins installed, resulting in the "recent" one being non-existent.

Thoughts?

**Comment by willnationsdev** [comment]
If you end up switching it to the project settings, then all you should have to do is use `ProjectSettings.add_property_info` to add the new setting and then `get_setting` and `set_setting` to access it.

**Comment by Xrayez** [comment]
Yeah, I think there could be a separation between plugin settings and cached data which could be temporary in nature. If recently used plugin is stored in project settings, then it could create noise in VCS if dealing with `ProjectSettings` itself. 

It doesn't fail if a recent plugin doesn't exist in other projects anyway because it actually searches through the available plugins to match against.

It haven't occurred to me that those temporary settings could be stored per project indeed, so yeah I could look into that later.

**Comment by Xrayez** [comment]
Well the change was simple actually:

```gdscript
var dir = get_editor_interface().get_editor_settings().get_project_settings_dir()
```
instead of:
```gdscript
var dir = get_editor_interface().get_editor_settings().get_settings_dir()
```

It saves the config at path like this per project now:
`C:\Users\Xrayez\AppData\Roaming/Godot/projects/my-project-8bc1742e6224b66a45cc2da4138d7ee7/plugins/plugin_refresher/settings.cfg`

So seems ok as I see there are other project settings related configs there.

**Comment by willnationsdev** [comment]
Alright. Looks good to me, afaik. Thanks so much!

**Pull request merged**
